language: node_js
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
branches:
  only:
    - master
    - develop
    - /^greenkeeper/.*$/
install:
  - npm install
before_script:
  - npm install -g gulp-cli
  - npm install -g webpack
script:
  - NODE_ENV=production npm run build